### ISSUE TITLE
No results found appears when resetting search with a large range.

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#10]
How to reproduce: 
1.  Open the app (make sure you don't do anything else before the next step).
2.  Connect to any game as usual.
3.  Go to the search tab.
4.  Set Seach Range to `Unknown` and set the range from 10000000 - 11000000.
5.  Press [Search].
6.  Since [Restart] is greyed out, Press [Undo] and press [Yes]
7.  Press [Restart] and press [Yes]
8.  Press [Search] again.
If done correctly, you will get an error saying No results found, even though it was supposed to be your first search again.

Even if I were to say no, the search button would be grayed out and unclickable. This can be a problem if I accidently did an unknown search in the wrong area and wanted to do it over again. I tested with `16-Bit` and `32-Bit`.

The weird thing is that if I were to do a smaller search, such as set the range from 10000000 - 10001000, and press the [Restart] button, the bug would go away when doing a new search with a bigger range! I can also press the [Restart] button without needing to press the [Undo] button.

**Comment by BullyWiiPlaza** [comment]
I can reproduce this and I just corrected some problems so the search should be optimized now (also fast with big memory ranges).
