### ISSUE TITLE
JGecko U closes unexpectedly on Linux

### ISSUE THREAD

**Issue by RxdRvse** [BullyWiiPlaza/JGeckoU#102]
Alright so disregard this if you dont wanna deal with it but I'm trying to open jgecko on Linux and after installing Java i do the open jar command in the directory. Everything seems to work fine and the menu comes up but only for a split second then closes itself right after. I installed both openjdk-8 and 11 and tried both separately both with the same result. The only thing I noticed that could be a problem is in terminal it says "System is not 64-bit" Which is true since I am using a 32-bit OS. Seeing as how that is the case would that mean it wont work on this specific device? some feedback would help greatly, thanks. Also love your work, sorry people dont appreciate it.

**Comment by RxdRvse** [comment]
Also by looking in past issues I saw someone who experienced something similar and said it was the settings file. I know this is most likely not the issues but I tried deleting it in case and it reinstates itself into the folder. I know this likely isnt the issue so disregard if you feel the need to.

**Comment by BullyWiiPlaza** [comment]
Hi, thanks for your issue. I can confirm this bug on Ubuntu 64-bit. Your OS bit version does not matter, the `System isn't 64-bit...` message is only a hint and not a fatal error. I even get Java VM crashes on Linux and other times no feedback at all and the application just exits. I'm looking closer into this.

**Comment by BullyWiiPlaza** [comment]
Alright. after investing some time into it, I found the bug. It's fixed now with the latest version. 👍
