### ISSUE TITLE
Not really an issue but a concern

### ISSUE THREAD

**Issue by Korozin** [BullyWiiPlaza/JGeckoU#104]
So as I've noticed there is a donation feature for people to buy the code wizard and etc. Which isnt the concern, the donations are fine; the concern is that someone could just go to the Forks page and download a version from 2 years ago and "seemingly" get all the locked features. I'm sure you're aware of this but I personally don't wanna see people just go and get a forked version and you get completely run around on because your work does actually deserve compensation. There may not be a way to do anything about this and I'm almost positive you're aware of this but I just felt I should say something ig. Have a good day

**Comment by BullyWiiPlaza** [comment]
@Korozin Yeah, it is what it is. They should take it down. I added many improvements and bug fixes to the latest version so it's not really worth it for them at the end of the day. I should have handled this better before but the community just doesn't make me feel appreciated enough so I launched the donator features (a bit too late).
