### ISSUE TITLE
When spamming the [Write] button in the Memory Viewer tab, the ui freezes.

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#11]
If you have Auto Update turned on, then just pressing [Write] once will freeze the ui, user interface. However, if you have it off, keep spamming the button (press it nonstop until the ui does not respond anymore) and the ui will soon not respond.

Switching tabs, pressing the reconnect/disconnect button, or interacting with anything on the app with not work. Also, resizing the UI results in this:
![image](https://cloud.githubusercontent.com/assets/3105794/17868099/24aeddba-6862-11e6-8f1c-645e9e388366.png)

Even if I force quit the app, I would not longer be able to reconnect the to Wii U and have to reset the Wii U in order to reconnect again.

**Comment by BullyWiiPlaza** [comment]
Indeed. For me, it doesn't corrupt the codehandler server but regardless I fixed the issue so you can spam all you want and nothing bad happens.
