### ISSUE TITLE
When setting the search range to a very big range, it stays stuck on Search.

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#13]
First off, I want to say thank you for fixing all these bugs that I have been reporting recently! I really appreciate it!

So I have been trying to dump from the range 30000000 to 40000000 with JGecko U. I noticed that it is stuck with the unclickable button saying `Search`. So far, it seems like I have been able to reproduce this consistently. It stays like this for hours; I left it on last night and it still had the same unclickable button.

Here is a picture for reference of what settings I picked:
![screenshot from 2016-08-23 21-32-09](https://cloud.githubusercontent.com/assets/3105794/17918567/eee87e56-697a-11e6-89c6-ca63bd56e433.png)

**Comment by BullyWiiPlaza** [comment]
I noticed that I'm smashing the RAM by backing up every search result for the undo feature. :/
This has been changed now but I'm not sure if this fixes your issue. I seem to have problems with big searches, too.

**Comment by CuriousTommy** [comment]
It seems like the issue is still there, unfortunately (at least leaving it on for an hour or so).

**Comment by BullyWiiPlaza** [comment]
It should be fixed now. I did very big searches successfully

**Comment by CuriousTommy** [comment]
Thanks BullyWiiPlaza!

Because of school, I don't have time to test it. But I'll take your word for it.
