### ISSUE TITLE
CosmoCortney's Codehandler link broken

### ISSUE THREAD

**Issue by MKWPlayer1337** [BullyWiiPlaza/JGeckoU#15]
as the title says. Was it removed due to copyright claims or something like that?

**Comment by BullyWiiPlaza** [comment]
No, which link? His website link is unreliable so I removed it from the application

**Comment by MKWPlayer1337** [comment]
Okay. I see. Sorry about that. I just needed that for J Gecko U to run codes using that codehandler.

**Comment by SirNapkin1334** [comment]
Are there other places to get the codehandler?

**Comment by BullyWiiPlaza** [comment]
It is included already. Read the instructions. You obviously didn't even try it before asking.
