### ISSUE TITLE
Using the Floating Point -> Hexadecimal with a negative number gives different result then expected.

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#16]
For example, when I put `-20`, I expected it to be `c1a00000`. However, when I type `-20` in the input field, I get `-3E600000`.

**Comment by BullyWiiPlaza** [comment]
Fixed!

![2016-09-13_10h55_35](https://cloud.githubusercontent.com/assets/7620135/18467550/ae03c4f0-79a0-11e6-9e3e-ee50440840aa.png)
