### ISSUE TITLE
JGeckoU won't start!

### ISSUE THREAD

**Issue by MarioMario54321** [BullyWiiPlaza/JGeckoU#18]
I installed TCPGecko on Homebrew with CosmoCourtney's Code Handler, but when I click Connect, it won't connect! What's wrong? I have the latest version of TCPGecko and JGeckoU and everything.

When I try auto-detect, it freezes, but when I connect with the right IP address, it gives me the error that the game title (by the game code) is not in the database. What is wrong??

**Comment by BullyWiiPlaza** [comment]
Wiiubrew might have been down

**Comment by MarioMario54321** [comment]
In that case, it still is. How long until you can get it back up again?

**Comment by BullyWiiPlaza** [comment]
It already works for me the whole time, it doesn't seem to be down...

**Comment by MarioMario54321** [comment]
I see the problem now. Not every game is listed under Titles. Some titles like Super Mario 3D World are missing. Can you fix this?

**Comment by BullyWiiPlaza** [comment]
It has to be added to http://wiiubrew.org/wiki/Title_database by someone then because it pulls it from there
