### ISSUE TITLE
Doesn't work with eShop downloaded games!

### ISSUE THREAD

**Issue by MarioMario54321** [BullyWiiPlaza/JGeckoU#19]
For some reason JGeckoU doesn't work with eShop downloaded games! It just gives me this error:

Connection timed out

Does it only work with disc games? Or is there a way to have it work with digital games?

**Comment by BullyWiiPlaza** [comment]
Funny how [someone used it on Super Mario 64](http://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/page-209#post-6884682) so apparently it works when you installed TCP Gecko. Or am I mistaken?

**Comment by MarioMario54321** [comment]
The game I tried it on was a legit digitally downloaded copy of Shantae and the Pirate's Curse. Maybe it won't work because it's a WayForward game? I heard Loadiine can't play ripped WayForward games. It's just that someone posted WiiU cheat codes for the European version of this game.

**Comment by BullyWiiPlaza** [comment]
This can't be fixed in JGecko U. Either it is possible to connect or not. The Wii U has to have the TCP Gecko installed correctly.

**Comment by MarioMario54321** [comment]
I was sure to install it correctly. When it gave me the black screen with text, I pressed X, which installs the codehandler.
