### ISSUE TITLE
Memory search evaluating bytes may freeze

### ISSUE THREAD

**Issue by BullyWiiPlaza** [BullyWiiPlaza/JGeckoU#20]
Reported [here](http://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/page-211#post-6898913).

This happens because the search results take up too much memory. It is not a bug.

Starting the application with more memory will help:
`java -jar -Xmx10g -Xms10g "JGecko U.jar"`
This would assign `10 gigabytes` of memory to the process instead of only around `3.8` by default.

Note:
This is automatically done by `JGecko U` now. Unless it causes big problems, it will stay that way.

**Comment by CuriousTommy** [comment]
So I did a quick test on Super Mario 3D World for a 32bit unknown search from `30000000 - 4CD9FFFF` and was able to find the timer address for save one!

**Comment by BullyWiiPlaza** [comment]
But the update is released just now 👍
