### ISSUE TITLE
[Feature Request] Search for String support

### ISSUE THREAD

**Issue by dragonbane0** [BullyWiiPlaza/JGeckoU#21]
Is this on the roadmap already by any chance? It's the only reason to still use the old messy tcpgecko sometimes lol I've gotten used to search for the byte expression of the string at this point, but its still kinda inconvenient, so that would be great to add :)

**Comment by dragonbane0** [comment]
Or you just use the right mouse button. How did I never figure that out lol

**Comment by BullyWiiPlaza** [comment]
Yeah, you can use the search tab and put a string, then convert to hex and search. Of course the length is limited but that shouldn't be a big deal.
