### ISSUE TITLE
JGeckoU freezes

### ISSUE THREAD

**Issue by ElectroArc** [BullyWiiPlaza/JGeckoU#23]
JGeckoU freezes when i connected with Breath of the wild and go to the memory viewer JGeckoU freezes

**Comment by BullyWiiPlaza** [comment]
I don't think so, other people are using it just fine. Can you give more details and did you read the setup guide?

**Comment by ElectroArc** [comment]
yes I readed it and i can use JGeckoU for all other games but by BOTW it freezes by memory viewer

**Comment by BullyWiiPlaza** [comment]
Which address are you trying to view?
