### ISSUE TITLE
Not able to connect JGeckU to my WiiU

### ISSUE THREAD

**Issue by superior571** [BullyWiiPlaza/JGeckoU#24]
My JGeckoU client is not connecting to my WiiU even though I followed all the steps correctly. I uploaded the logs. My PC is connected with LAN and my WiiU with WLAN but it's the same network. I tried it with a disc game as well as with a downloaded one. My PC is on Win7 and I have the latest Java installed.

[2017-03-15-13-45-25.txt](https://github.com/BullyWiiPlaza/JGeckoU/files/844508/2017-03-15-13-45-25.txt)

**Comment by BullyWiiPlaza** [comment]
Invalid because of user error in setting it up correctly themselves. Inability is not a bug.
