### ISSUE TITLE
Trouble getting JGecko U to connect to Wii U

### ISSUE THREAD

**Issue by L3nggao** [BullyWiiPlaza/JGeckoU#28]
Is it a normal US issue where sometimes I can connect to my Wii U with JGecko U, by chance and it usually has a hard time connecting? 

I do it step by step, by the book, even watched multiple videos to see if I missed one, and every single time. 
It seems to be base on luck for me, probably because I'm in the US.
![issue](https://cloud.githubusercontent.com/assets/26612835/24279814/37bacd64-101a-11e7-8fac-ffbfb6df5770.PNG)

I've tried it on a different Laptop too, incase it was this one's fault, but the same case happens with different warnings, which said something about not being able to connect or no connection.

**Comment by L3nggao** [comment]
I've been able to accidentally connect twice, but that was by chance.

**Comment by BullyWiiPlaza** [comment]
Are you also using the Homebrew Launcher version? For me, connecting with the Homebrew Launcher version works flawlessly.

**Comment by linkkokir** [comment]
yeah it happens to me too

**Comment by linkkokir** [comment]
bully please help

**Comment by BullyWiiPlaza** [comment]
Sorry but since for almost everyone connecting works without fail and it works fine for me, I can't work on a fix. There is no bug, it must be your network or something I don't have control over with JGecko U. Restart your router maybe or try another one if you can?

**Comment by linkkokir** [comment]
Ok thanx for ur help bully ill take that in consediration

**Comment by linkkokir** [comment]
Bonjour,
Je viens de signer la pétition "Susan Wojcicki: Restore Etika's YouTube
channel so we can remember his legacy | RIP Desmond Amofah" et je
souhaitais savoir si vous voudriez nous aider en ajoutant votre signature.

Notre objectif est d'atteindre 50 000 signatures et nous avons besoin de
plus de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chng.it/YZpT6JJPrg

Merci!
Ened
