### ISSUE TITLE
JGeckoU for 5.5.1

### ISSUE THREAD

**Issue by mkCody** [BullyWiiPlaza/JGeckoU#3]
Hi. I wanted to know if JGeckoU was working yet on 5.5.1. Some people say it does and some say it doesn't. When I tried I freeze, but I just need to know if it does or not. :joy: Thanks.

**Comment by BullyWiiPlaza** [comment]
[Yes](http://gbatemp.net/threads/jgecko-u-setup-guide.426292/#post-6341209).
