### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Rendaman13** [BullyWiiPlaza/JGeckoU#30]
I have followed the setup exactly, and successfully installed tcpgecko via homebrew. However, upon entering my game and attempting to connect, jgeckou can't seem to find my wii u. In fact, nothing can find my wii u, not even Advanced Ip scanner. Both computer and console are connected to the same network. Any and all help is appreciated.

**Comment by BullyWiiPlaza** [comment]
This is NOT an issue but your user stupidity. Please don't open issues when it's not a bug. If nothing can find your Wii U, fix your network setup/connect it to the same WiFi connection.
