### ISSUE TITLE
Console Crashes with newer builds of Gecko when using WiiU-VC-Inject

### ISSUE THREAD

**Issue by danne2** [BullyWiiPlaza/JGeckoU#31]
So WiiU-VC-Inject is a pretty outdated tool but it's the only method I'm aware of of generating GBA injects on the WiiU.

Using newer builds of Gecko, the console crashes with the message 
"Illegal command byte received 0x72. Server version 5/27/2017. If you see this you most likely have to update your TCP Gecko Installer"

Using old builds of Gecko (I tested with v1,0), it works fine. Not really sure if it's a deprecated feature or an actual bug.

**Comment by BullyWiiPlaza** [comment]
0x72 is the old memory search command. It has already been removed from JGecko U so you must be doing something wrong. Please download the newest versions of both and explain which VC injection you're using by linking to it.
