### ISSUE TITLE
Not opening..?

### ISSUE THREAD

**Issue by RJ-Kio** [BullyWiiPlaza/JGeckoU#34]
I downloaded the .jar file and instead of having the Java symbol next to it, there's one for Internet Explorer. I've tried opening it anyway, and it shows the IE browser and what I should do with the file. It didn't open when I chose so, but asked if I should save it again. How do I get JGecko U to open without using IE?

**Comment by skoolzout1** [comment]
Make sure you have Java SDK installed. And right click the .jar file and select "Open With..." And then select Java as the application to open it with, and select the checkbox that says "Always use this to open files of this type" or something along those lines. And you should be good
