### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by willebug** [BullyWiiPlaza/JGeckoU#35]
![j gecko](https://user-images.githubusercontent.com/28664838/27849404-faaf4cc2-611a-11e7-9127-1154384e31ee.png)

Getting the errors on the attached photo.  I'm able to use other applications such as Saviine.  Any advice?

**Comment by skoolzout1** [comment]
- Make sure TCPgecko is up to date. Get the lasted Update by clicking the Installer button in the Miscallaneous tab in Jgecko.
- Make sure you use the correct IPv4 address for your Wii U. When launching TCPgecko it tells you your Wii's IP at the top.

- Try disabling your antivirus as they sometimes block TCP connections if the connection seems untrustworthy.

**Comment by willebug** [comment]
Sorry I should have been a little more descriptive. All of the above have been done. Downloaded and installed tcp gecko version 2.3 I believe and just downloaded j gecko u from GitHub. Firewall and antivirus are off and the IP address is verified correct.

**Comment by skoolzout1** [comment]
Have you tried connecting to different games?

Also, when connecting, does the title of the game pop up in the Top Bar on the left?

**Comment by willebug** [comment]
I tried Breath if the Wild and Twilight Princess. And nothing populates it just gives the pop up and suggests that I follow the setup guide.

**Comment by skoolzout1** [comment]
Hmmm. It's probably something super obvious that you and I are both not thinking of.

The only other things I can think of are:

-Make sure you are connected to the same network as your Wii u. Most likely this is done but you never know. I've accidentally done this before lol.

- if you are using a LAN cable/Ethernet cord, try using wifi instead. Again this shouldn't make a difference but you never know. 


You are launching TCPgecko through the homebrew channel correct? Like you go through the black screen that says press A to install TCPgecko on your Wii u?

**Comment by willebug** [comment]
Yeah I'm on the same network and I'm launching tcp gecko from the home brew channel. I've tried it both with and without running mocha and that doesn't seem to help. I'm wondering if there is something not quite right with the way I have my Wii U setup. I was able to use the BOTW trainer until the recent update for obvious reasons and I'm trying to use this now.

**Comment by BullyWiiPlaza** [comment]
Connection errors like that aren't program bugs, they're user network setup errors/firewall configuration rules/anti virus whatever. Make sure you're not blocking the connection somehow. This has to be fixed by you and not the program because it obviously works in general given the right circumstances.

**Comment by Aurisvida** [comment]
I have the same issue but I tried other games like SM3DW, Splatoon and it worked TPHD is the only game that does not work
