### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by Megabyte918** [BullyWiiPlaza/JGeckoU#36]
Hello, I'd like to request some features that I've been thinking of for a while now. Let me know what you think!

1) ~~The memory viewer tab auto-updates pointers as well. I was thinking it would be cool to have it so if you insert pointer notations into the address bar while "auto update" is checked, it keeps following the pointer to it's destination address (as long as the destination address is valid). I was testing some pointers today and it got kind of tedious how I would have to keep clicking the follow pointer button then copy/paste the pointer every time i loaded something that changed the pointers destination address. I think something like this would be much easier if it just auto-followed the pointer. Maybe if something like this was implemented, the name before the address bar could be changed from "Address: ___________" to "Address/Pointer: _____________"? or maybe have a checkbox next to the address bar similar to auto-update, but it would be for pointers instead? I'm not exactly sure~~

2)  Values inside the "Current" tab of Search results change colors when the value has changed. This is a feature that I saw on Cheat Engine that I thought would be very useful on this program as well. For example, your searching for health in a game and you've narrowed down the results to about 100 or so addresses. You change the value of your health in game, but instead of narrowing down the addresses by searching over and over again, you scroll down the 100 results, and see the only value in the current tab that's text color has changed to red. Which means the value has changed. I think a feature like this would be extremely useful, it would be much faster and more efficient than just guessing or poking random addresses until you find the right one.

**Comment by BullyWiiPlaza** [comment]
> have a checkbox next to the address bar similar to auto-update, but it would be for pointers instead?

I like that
Values inside the "Current" tab of Search results change colors when the value has changed.
This is like auto-updating but it's too slow to be useful most likely. Reading memory from the Wii U is not like doing it directly from the PC like `Cheat Engine`. I'll see about that though

**Comment by skoolzout1** [comment]
Doesn't the watch list effectively follow pointers constantly already?

**Comment by BullyWiiPlaza** [comment]
Yeah, it does. This is a bit pointless

**Comment by Megabyte918** [comment]
Oh crap, how could I have forgotten about the watchlist! I have to use it more often thanks for reminding me :P  I will cross it off the list

Speaking of the watchlist.. I have a few feature requests for it that I think would be neat. 

1. An option to change the displaying value type of values within the "value" section? For example if i'm watching a pointer and I want to know what the current value of its destination address in decimal is, I would click modify watch, then change an option that said "value type". Kind of like how it is with being able to change the value size

2. An option to view the destination address of an address expression in the memory viewer. Just like how you can right click a search result and press view it memory viewer, but with watch list items

Sorry for so many requests haha, I just had to get these off my chest

**Comment by BullyWiiPlaza** [comment]
I did the requests except for the value color change. This is what you use the memory viewer and search refinements for. 👍
