### ISSUE TITLE
CONSTANT CRASHING! >:(

### ISSUE THREAD

**Issue by iDartix** [BullyWiiPlaza/JGeckoU#37]
Tried Mario Kart 8 and Black Ops II on JGeckoU but keeps crashing. Tried different web methods for hombrew and TCPGecko. I managed to get some random Mario Kart 8 Trainer to work completly fine but your tool JUST WONT WORK!!!!! >:(

**Comment by skoolzout1** [comment]
update TCPgecko..

Jgecko even has its own button that will download the latest version for you.

Its the External tools -> TcpGecko installer button.

No need for angry faces.
