### ISSUE TITLE
DELETING ALL MY CODES!!!!!!!!

### ISSUE THREAD

**Issue by iDartix** [BullyWiiPlaza/JGeckoU#38]
Spent ages putting codes in and i cant save them for some reason and as soon as i load fucking mario kart my wii u freees and delets all of my fucking codes WTF!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by skoolzout1** [comment]
Read and watch some tutorials again buddy. You're missing something. It's not Jgecko.

**Comment by BullyWiiPlaza** [comment]
Wow, really? Please don't post anymore, thanks.
