### ISSUE TITLE
JGeckoU can't connect when TCPGecko is installed via SwapDRC

### ISSUE THREAD

**Issue by wiiarctus** [BullyWiiPlaza/JGeckoU#39]
Hey, I wanted to test some Splatoon codes but don't have a monitor available atm so I started SwapDRC and installed it plus TCPGecko. In Splatoon I was about to connect with JGeckoU and then all of a sudden it crashed and gave me a error. The console even froze one time when I tried to connect with.^^

[2017-08-17-21-26-37.txt](https://github.com/BullyWiiPlaza/JGeckoU/files/1232423/2017-08-17-21-26-37.txt)
[2017-08-17-21-37-53.txt](https://github.com/BullyWiiPlaza/JGeckoU/files/1232424/2017-08-17-21-37-53.txt)

**Comment by BullyWiiPlaza** [comment]
Read the readme and download the newest version.

**Comment by wiiarctus** [comment]
So no way of getting it connected? :/

**Comment by BullyWiiPlaza** [comment]
Probably yes but it can't function correctly/will crash/freeze up.

**Comment by wiiarctus** [comment]
And only the creator of SwapDRC could fix this issue..?

**Comment by BullyWiiPlaza** [comment]
Yes but he obviously won't, it would be too much work.

**Comment by wiiarctus** [comment]
Damn and the problem with the Lite version is that if I start it, it works fine and all but if start the HBL and then TCPGecko it wont work anymore and loses its functionality.
