### ISSUE TITLE
Generated Code Format Problem

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#4]
When I use the code generator, it seems to format the code differently. (Sorry it the image is too big)
![screenshot from 2016-05-21 21-54-45](https://cloud.githubusercontent.com/assets/3105794/15452306/d819633c-1f9e-11e6-87bd-384abc7840c5.png)

The numbers are right, it is just how the numbers are aligned. I am using Arch Linux with Gnome.
```
00220000 3FB467E0
10000000 50000000
00000024 00000000
10000000 50000000
000002E8 41000000
```
Tested with recent version of this program (https://github.com/BullyWiiPlaza/JGeckoU/commit/26165a6ae90037dca00ce4a9bd8508351d960206) from the time the message was written.

**Comment by BullyWiiPlaza** [comment]
On Windows for instance it is correctly formatted:
![screenshot](http://fs5.directupload.net/images/160522/u3yqoeeu.png)
But I think I know why this happens so I'll fix it.

**Comment by BullyWiiPlaza** [comment]
Fixed. Thanks for the report.

**Comment by CuriousTommy** [comment]
I tested it; the issue is fixed! Thank you!
