### ISSUE TITLE
Download Code Database wiiucodes.tk is domain parked

### ISSUE THREAD

**Issue by CeruleanSky** [BullyWiiPlaza/JGeckoU#40]
The Download Code Database codes from wiiucodes.tk feature is non functional.  The domain now redirects to http://domain.dot.tk/ parking service.

**Comment by BullyWiiPlaza** [comment]
Why are you telling me that when I didn't make the website?

**Comment by CeruleanSky** [comment]
When you click ```Download Code Database ``` an error occurs.  The help text says it tries to download from wiiucodes.tk , perhaps you can include a local copy of the database with the app, or an alternative place to download the codes.

**Comment by BullyWiiPlaza** [comment]
There is no alternative and it sucked anyway.

**Comment by OscarOG** [comment]
http://cosmocortney.ddns.net/codes/wiiu/
Not so much but is a beginning.

**Comment by BullyWiiPlaza** [comment]
Alright but I would have to code support for this site, it's not made easily for programmatic access though it's possible.

**Comment by BullyWiiPlaza** [comment]
Since the original issue was about the Wii code database which no longer works, this is closed. I opened another issue for the CosmocCortney website support.
