### ISSUE TITLE
Cannot connect continuous error message for CEMU

### ISSUE THREAD

**Issue by GitHubDan01** [BullyWiiPlaza/JGeckoU#43]
I am trying to use the codes for BOTW using CEMU i am using the localhost IP address 127.0.0.1 all i keep getting is the same error message and iv been attepting this for the past 3 hours 

![jgeko u issue for cemu](https://user-images.githubusercontent.com/32972014/31846663-8da0d5ce-b606-11e7-9bbe-dd4056d0d781.png)

**Comment by BullyWiiPlaza** [comment]
You can't. It has to run the TCP Gecko Installer. It's only for real Wii U's.
