### ISSUE TITLE
about patch assembler

### ISSUE THREAD

**Issue by xspeedfly** [BullyWiiPlaza/JGeckoU#49]
i tried 2 type assembler code

`C2000000 0B5E6BE8
FC000018 00000000
D0000000 DEADCAFE`

`C2000000 0B5E6BE8
FC000018 00000000`

use your's tcpgekco.elf with built-in code handler or othe code handler

send codes have effect,but must be just disable codes,codes effect still have,if not will freeze game,my code error or not support always enable?

and only send 1 project per 1 time,if select 2 project or above will freeze game

**Comment by BullyWiiPlaza** [comment]
`C2` isn't a valid code type.
Please read the documentation before you open an issue anywhere:
http://cosmocortney.ddns.net/enzy/wiiu/cafe_code_types_en.php

**Comment by xspeedfly** [comment]
thant documentation mean Patch Assembly use C2

![c2](https://user-images.githubusercontent.com/13378208/34463676-7d6a665e-ee9e-11e7-8f03-5109264a850f.png)

**Comment by BullyWiiPlaza** [comment]
Oh, sorry. I didn't make the code types, please ask CosmoCortney:
http://gbatemp.net/members/cosmocortney.327808/
I think you can only have 1 C2 code at a time similar to C0.
