### ISSUE TITLE
Cheat Codes Can Be Accidently Deleted!

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#5]
Here is how you can reproduce it:

> 1. Turn off Auto Save.
> 2. Connect to the game as normal and add cheat codes.
> 3. Click Store Code List.
> 4. Disconnect from game.
> 5. Click Store Code List again.
> 6. Connect.

The result is that all the codes for the game you connected to are gone. 

I have also had an issue where my cheat codes were gone when auto save was enabled (It tends to happen when I switch between Gecko dotNet and JGecko); however, I am not sure if it is related to this issue.

**Comment by BullyWiiPlaza** [comment]
Yeah, because the previous game is still "remembered". This is bad and I will fix it right now.

**Comment by CuriousTommy** [comment]
Tested, it does not delete the codes, thank you!
