### ISSUE TITLE
Setting a directory

### ISSUE THREAD

**Issue by boss69xd** [BullyWiiPlaza/JGeckoU#50]
Can i set a directory for the auto save logs? Because it fills up my desktop.

**Comment by BullyWiiPlaza** [comment]
The directory is set to `logs` relative to `JGecko U.jar`. It does not fill up the desktop because the files are written into that sub directory.

**Comment by boss69xd** [comment]
This happens http://prntscr.com/i34ygj

**Comment by BullyWiiPlaza** [comment]
No. The files are written to the `logs` folder only. See the screenshot:
![image](https://user-images.githubusercontent.com/7620135/35186423-32f34ade-fe14-11e7-9237-9ded8d77ed58.png)
Please download the latest version. It definitely won't write any logs to the `Desktop`. How exactly do you even manage to make this happen? What's the process?

**Comment by boss69xd** [comment]
I open JGecko U, load a code list, then when moving, editing, ticking codes, and unticking codes.
It puts a logs on my desktop even with the logs folder there.

**Comment by boss69xd** [comment]
What i mean by logs is this
when ever i do anything in my code list one of those appear, it would be nice to have all of them appear in one folder. 
![screenshot_6](https://user-images.githubusercontent.com/30028455/35195193-7706bd66-fe85-11e7-9be4-c588242716cf.png)

**Comment by BullyWiiPlaza** [comment]
Those are the code list backups, not logs. I fixed it now. Let me know if it's fine.

**Comment by boss69xd** [comment]
Ok its fixed now thanks
