### ISSUE TITLE
please add write more line code

### ISSUE THREAD

**Issue by xspeedfly** [BullyWiiPlaza/JGeckoU#51]
because C2 code only write 1 line per time,so Jgeckou possible to add write multiline mode like apply in memory viewer option,thanks

**Comment by BullyWiiPlaza** [comment]
You can use the `Upload File` function (memory viewer -> right-click -> `Upload File`).

First, create a file with assembly code in it. Then upload it to the address you want. Now it's written. (This works at assembly and data addresses).

Does that solve your problem?

**Comment by xspeedfly** [comment]
thanks for your advice,i will try it

**Comment by xspeedfly** [comment]
i tried it,great than use C2 code,but only can write continuous address,maybe use text file upload by regular addresses and values is better

**Comment by BullyWiiPlaza** [comment]
So you want to upload address value pairs in a text file like this instead of continuous binary values?

`02000000 10000000`
`02000004 20000000`
`02000100 10000000`

**Comment by xspeedfly** [comment]
yes,i want this effect,because any cheat need from code line jump to empty line to make

**Comment by BullyWiiPlaza** [comment]
Added now.

**Comment by xspeedfly** [comment]
thanks very much
