### ISSUE TITLE
Searching Issue

### ISSUE THREAD

**Issue by Rainchus** [BullyWiiPlaza/JGeckoU#53]
![image](https://user-images.githubusercontent.com/22468522/37263345-b5b774e4-2575-11e8-8f9b-b3a5bddbc631.png)
I receive this issue every time I try to search, no matter what type of search I do

**Comment by BullyWiiPlaza** [comment]
Check this issue:
https://github.com/BullyWiiPlaza/JGeckoU/issues/20

**Comment by Rainchus** [comment]
Ah ok. So now it works, but im getting an issue with it not changing my RAM when I edit it. I also tried writing a code and sending it to the console to do so, but that did not work either.

**Comment by BullyWiiPlaza** [comment]
Read the code type documentation: http://cosmocortney.ddns.net/enzy/wiiu/cafe_code_types_en.php

**Comment by Rainchus** [comment]
Ah my bad. I made a mistake in the search. I assumed the default memory was the correct memory region. Thanks a lot for the help, I really appreciate it :)
