### ISSUE TITLE
Code database links for Wii U does not work. Any link for working one?

### ISSUE THREAD

**Issue by lovrenco** [BullyWiiPlaza/JGeckoU#60]
Is there full list of working codes for PAL games? Online or downloadable collection.

Thanks.

**Comment by BullyWiiPlaza** [comment]
There is e.g. http://follow-the-white-rabbit.net/page.php?topic=wii_u_cheats but I don't know any other good ones. There never has been a good database to begin with. Also this issue isn't really related to JGecko U suggestions or bugs so I'm closing it. It's better to ask on GBATemp or something.
