### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by BossXD** [BullyWiiPlaza/JGeckoU#64]
![Screenshot_3](https://user-images.githubusercontent.com/30028455/57150179-35199580-6d93-11e9-9b26-72c4b96a7fec.png)
![Screenshot_5](https://user-images.githubusercontent.com/30028455/57150180-35199580-6d93-11e9-9020-cfe5a5d3108d.png)
![Screenshot_4](https://user-images.githubusercontent.com/30028455/57150181-35199580-6d93-11e9-9010-9554752bb889.png)
![Screenshot_2](https://user-images.githubusercontent.com/30028455/57150182-35b22c00-6d93-11e9-8d46-f97a99dd5572.png)

A few glitches. 
This has only happened since installing java 11

**Comment by BossXD** [comment]
This happens on java 12 too. 
It doesn't happen on java 8 though.

**Comment by BullyWiiPlaza** [comment]
Thank you for the follow up, I will look into this in a month or so when I'm back home. Sorry for taking so long but life gets in the way sometimes. :)

**Comment by BossXD** [comment]
> Thank you for the follow up, I will look into this in a month or so when I'm back home. Sorry for taking so long but life gets in the way sometimes. :)

It's ok, i understand. Take your time.

**Comment by BullyWiiPlaza** [comment]
Someone made a similar issue like this one so maybe it helps you fix your problem as well?
https://github.com/BullyWiiPlaza/Universal-Pointer-Searcher/issues/9

**Comment by BossXD** [comment]
That did work, but, everything is lower quality now, if that makes sense. 
Here, compare this image to your client without the Java.exe edits: 
![screenshot](https://user-images.githubusercontent.com/30028455/64467725-3e23c600-d0e9-11e9-8580-ee3c7a1b0ca2.png)
I don't know if you can tell a difference, it seems more blurry(?) to me. So i would recommend you fix the issue so people don't have to go into their java files and mess with stuff (and potentially break something important).

**Comment by BullyWiiPlaza** [comment]
There is nothing to fix because it's not a `JGecko U` bug if it's due to a different Java version and it sounds similar to this: https://bugs.openjdk.java.net/browse/JDK-8187367
Nothing stops you from still running `Java 8`. All of my Java tools right now support `Java 8`.

Also you can try setting your display scaling to 100% in the display settings if you haven't done that yet.

**Comment by BossXD** [comment]
Yeah, your right its a display scaling thing, its not jgecko u, because changing it to 100% makes it work. But I'm not keeping it at 100% because I like it at 125%. So I guess I'll just have to wait until the bug is fixed on Java's end and deal with the "bad" quality of changing the java.exe and javaw.exe settings. 
I'm using 1920 x 1080 too, so that might be changing something(?).

And the reason I'm not using java 8 is because searching wouldn't work on java 8 for some reason, it would fail or give me an error.

**Comment by BullyWiiPlaza** [comment]
For the searching problem, check out this issue: https://github.com/BullyWiiPlaza/JGeckoU/issues/20
Make sure you have the `64-bit` version of Java as well.
