### ISSUE TITLE
Codes are not loaded from XML file

### ISSUE THREAD

**Issue by Mattkimmio** [BullyWiiPlaza/JGeckoU#65]
When I download Codes I can't open them. I can open them but there are no codes that popup

**Comment by Mattkimmio** [comment]
![lawuzkagwh](https://user-images.githubusercontent.com/50533432/57576301-07cb8800-7422-11e9-8a06-8f6e428b5d7e.PNG)

**Comment by Mattkimmio** [comment]
![lawuzuhg2 0 io edu ca ja uk us](https://user-images.githubusercontent.com/50533432/57576303-144fe080-7422-11e9-97a3-1eb8e45e8be3.PNG)

**Comment by BullyWiiPlaza** [comment]
How do you download the codes? Can you attach the file you're trying to load?

**Comment by Mattkimmio** [comment]
I can't because it is a xml file, but I can give you it zipped
[AGME01.zip](https://github.com/BullyWiiPlaza/JGeckoU/files/3170188/AGME01.zip)

**Comment by Mattkimmio** [comment]
It is from Splatoon HaxPack

**Comment by BullyWiiPlaza** [comment]
You have to place the XML into the codes folder of JGecko U. Only then it can be loaded successfully:
![image](https://user-images.githubusercontent.com/7620135/57586831-edfe7380-74fb-11e9-8ae0-36b55f8d4fd1.png)
Yes, this is a bug. Thanks for letting me know. I will fix it but you at least know the way.
