### ISSUE TITLE
Search ranges broken/certain search ranges don't work

### ISSUE THREAD

**Issue by BossXD** [BullyWiiPlaza/JGeckoU#69]
![image](https://user-images.githubusercontent.com/30028455/63068616-71ec4100-bed9-11e9-8bbe-30ec4cf84e4f.png)
![image](https://user-images.githubusercontent.com/30028455/63068633-816b8a00-bed9-11e9-90e7-e107b9f47245.png)

They worked before, why not now? am i doing something wrong? They were just working a little bit ago. 
Certain search ranges that are "bigger" don't work, littler ones do though. Is there something wrong or am i being dumb?

For example, this one doesn't work: 
![image](https://user-images.githubusercontent.com/30028455/63068762-0e164800-beda-11e9-8ce2-c78d57e3fe39.png)

But this one does: 
![image](https://user-images.githubusercontent.com/30028455/63068784-1c646400-beda-11e9-9420-4bf93ec63e38.png)

And in this case the search that doesn't work is smaller. Why?

**Comment by BossXD** [comment]
never mind lol
i had this checked: 
![image](https://user-images.githubusercontent.com/30028455/63069172-921cff80-bedb-11e9-954a-b09140ee4e6c.png)

**Comment by BullyWiiPlaza** [comment]
It doesn't matter if the range is big or not. It only depends on the memory ranges. To see the valid ranges, click the `Select Full Range` button. Usually reading/writing invalid ranges will crash your console so be careful when you disable the memory address protection feature which stops you from accessing them.
