### ISSUE TITLE
On linux "vdappc.exe not found!" was not found

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#7]
When you connect to a game and then go the Disassembler tab. You will be given this error: "vdappc.exe not found".

Since this is running on Linux, I would assume that the intended behavior would be to get the Linux version of vdappc and not the windows version.

**Comment by BullyWiiPlaza** [comment]
It has not been implemented yet for Linux but yes, you're right. Hopefully it will work with the Linux binaries. I will also test this later.

**Comment by BullyWiiPlaza** [comment]
I can't test on Linux since `VirtualBox` doesn't connect to my private network but I implemented support now.

**Comment by CuriousTommy** [comment]
I am assuming that you are suppose to place the vdappc in the same directory as the the JGecko U.jar, right?
![image](https://cloud.githubusercontent.com/assets/3105794/17638030/574ecb2c-609c-11e6-8a18-74c7fe329972.png)

**Comment by BullyWiiPlaza** [comment]
Not anymore. In the `/libraries/linux` directory

**Comment by CuriousTommy** [comment]
I might be doing something wrong here, but I still got the same error message.
![image](https://cloud.githubusercontent.com/assets/3105794/17640526/0f5d22fe-60b6-11e6-946f-ec5e62654711.png)

**Comment by BullyWiiPlaza** [comment]
Sorry, the folder should be called `unix` instead of `linux`.

**Comment by CuriousTommy** [comment]
I got the same error message.
![image](https://cloud.githubusercontent.com/assets/3105794/17644011/28955dca-6130-11e6-8d03-17ecce43aa15.png)

**Comment by CuriousTommy** [comment]
I saw the new update, but now it gives this error:
![image](https://cloud.githubusercontent.com/assets/3105794/17669309/0da01efe-62c2-11e6-9f11-8ed8678abc3a.png)

however, when I type that directory in the terminal, I am able to access it fine.

> [username@computername WiiU Software]$ libraries/unix/vdappc
> vdappc V1.3  (c)1998-2001 by Frank Wille
> PowerPC disassembler V1.4  (c)1998-2001 by Frank Wille
> Modified by Kenobi for WiiRd GUI 26/05/2008
> Modified by Link for Gekko instructions 04/08/2008
> Build date: Mar 11 2012, 00:09:09 (Gekko build!)

**Comment by BullyWiiPlaza** [comment]
Maybe because it's missing a leading forward slash? But in general I don't care, Unix is unsupported since I don't use it for development and can't connect to the Wii U in `VirtualBox` but if people can help me fix it then it's alright. It's funny how Java still has platform-independence problems even though I tried. Next update I will add the forward slash or whatever it takes to make this work

**Comment by BullyWiiPlaza** [comment]
I found the problem and fixed it in [this](https://github.com/BullyWiiPlaza/PowerPC-Assembly-Compiler
) tool for now.

However, the command line arguments seem to be invalid even though they are the same as on Windows. Observe the terminal for what happens. More information [here](http://gbatemp.net/threads/powerpc-assembly-compiler.415721/#post-6768044).

**Comment by BullyWiiPlaza** [comment]
Fixed now. I have to use the absolute path to the executables and `chmod` beforehand also
