### ISSUE TITLE
Throwing error while searching for codes

### ISSUE THREAD

**Issue by Wolfling1** [BullyWiiPlaza/JGeckoU#72]
Jgecko is throwing an error when searching for codes at around 49%

It happens on both my pcs

![image](https://user-images.githubusercontent.com/56173553/76171640-da478c00-6163-11ea-83c1-e73dda6ecbb5.png)

**Comment by BullyWiiPlaza** [comment]
https://github.com/BullyWiiPlaza/JGeckoU/issues/20
