### ISSUE TITLE
JGecko Stuck on Connecting

### ISSUE THREAD

**Issue by stealingroses** [BullyWiiPlaza/JGeckoU#76]
Sorry to bother again, but I'm having an issue where when I press connect, it gets stuck on connecting and the program is completely unresponsive. I tried restarting my console twice and reconnecting to tcpgecko from my homebrew menu, but no luck.

**Comment by BullyWiiPlaza** [comment]
You need to run my TCP Gecko Installer, no other. I just tested it and it works.
