### ISSUE TITLE
game not showing up

### ISSUE THREAD

**Issue by doinkdoink** [BullyWiiPlaza/JGeckoU#78]
hello I am using the latest version of jgecko and tcp installer and jgecko connects to my wiiu, but the game will not show up at the top like it doesn't recognize it. it previously worked on an older version o i do not think it is one of the games that does not work. its mh3u if you need to know. i tried it with two different games. i also have the latest version of titles.xml

**Comment by BullyWiiPlaza** [comment]
Did it already connect successfully? Because it still loads the game in the title after connecting.

**Comment by doinkdoink** [comment]
it connects successfully I believe because it gives me the option to disconnect. it won't load the title for me at all.

**Comment by BullyWiiPlaza** [comment]
I will test it tomorrow. Thanks for the hint.

**Comment by doinkdoink** [comment]
no problem. I also just tried a trainer for the game that works, so I do not think it is tcpgecko itself.

**Comment by BullyWiiPlaza** [comment]
Fixed.
