### ISSUE TITLE
Search Tab is not seen in the list of tabs

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/JGeckoU#8]
So I download the recent version, which at the time of writing is https://github.com/BullyWiiPlaza/JGeckoU/commit/cd095fa1eaa10b30fff25c6a5dbb0cef67821aac, aka Commit improved search tab. 

Going off of [your Youtube video](https://www.youtube.com/watch?v=e39I89BPOuM), The search tab should be between Dumping and Miscellaneous. But on the application, I don't see it.

![image](https://cloud.githubusercontent.com/assets/3105794/17828404/31d8650c-6645-11e6-9cb6-9ba2881cd87e.png)

**Comment by BullyWiiPlaza** [comment]
It wasn't released
