### ISSUE TITLE
problem gecko

### ISSUE THREAD

**Issue by charles198629** [BullyWiiPlaza/JGeckoU#80]
hello friend thank you very much for doing gecko regarding the update I have problems
I don't get the game title nor does the send code option appear enabled

I would appreciate your kind help.

best regards

**Comment by charles198629** [comment]
![Uploading 15955333487944347523432284180116.jpg…]()

**Comment by charles198629** [comment]
![Uploading 15955334234627044602788725759526.jpg…]()

**Comment by BullyWiiPlaza** [comment]
Fixed.

**Comment by charles198629** [comment]
What does that answer mean?

**Comment by BullyWiiPlaza** [comment]
Please re-download the newest version now.

**Comment by charles198629** [comment]
> Vuelva a descargar la versión más reciente ahora.

you are great friend
