### ISSUE TITLE
TCP gecko installer 

### ISSUE THREAD

**Issue by ultrasonicytb** [BullyWiiPlaza/JGeckoU#81]
Hello,

**Comment by ultrasonicytb** [comment]
when i'm trying to connect to my wii u with JGeckoU the app say that i havent the last version of TCP gecko installer but i've downloaded via the button on the app i don't know what to do
best regards
(sorry for the first comment)
![Bug](https://user-images.githubusercontent.com/41972298/88347687-a43e2980-cd4b-11ea-8f3f-f6f1ce2a9fc0.PNG)

**Comment by BullyWiiPlaza** [comment]
Read the setup instructions/README.
