### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by yuma-01** [BullyWiiPlaza/JGeckoU#82]
When im starting JGeckoU.jar an click autoconnect the Wii u shows this on the gamepad and TV (Image 2). Im doing what wrong?

TCPGecko Version: 2.51
JGeckoU: The latest version.

![Image_1](https://user-images.githubusercontent.com/68730464/88374444-12a9d880-cd9a-11ea-96c8-62b992865a01.jpeg)

![Image_2](https://user-images.githubusercontent.com/68730464/88374452-163d5f80-cd9a-11ea-88c9-b9ad956a6819.jpeg)

**Comment by BullyWiiPlaza** [comment]
I think this should be fixed already but I will try it again today (also with the Wii U Finder option).

**Comment by BullyWiiPlaza** [comment]
Okay, after thinking about this for a bit, you shouldn't use the auto detect option since it is slow/lags your PC and is actually fundamentally broken. Please enter your Wii U's IP address manually and press `Connect`.

**Comment by BullyWiiPlaza** [comment]
Actually, today I had another idea and managed to fix the auto connect feature. It will be usable in the next JGecko U update.
