### ISSUE TITLE
cannot send codes

### ISSUE THREAD

**Issue by asky78936** [BullyWiiPlaza/JGeckoU#83]
this does not let me send codes im connected also im using the new tcpgecko version

**Comment by BullyWiiPlaza** [comment]
Can you explain how exactly you can't send codes? Is the button greyed out or do you get an error message?

**Comment by asky78936** [comment]
the button is just greyed out idk why i have codes selected and im
connected also have just 4000 lines of code activated and im using the new
tcpgecko version, i should be able to send codes

**Comment by BullyWiiPlaza** [comment]
Make sure all codes are valid. Sending 4000 lines of code is working:
![image](https://user-images.githubusercontent.com/7620135/88463962-12532f80-ceb7-11ea-9740-421191a8c995.png)
Sending codes is enabled when you are connected, at least one code is selected and the code list isn't too long (less than or equal to 21248 code lines).
