### ISSUE TITLE
JGecko Closes Every So Often

### ISSUE THREAD

**Issue by doinkdoink** [BullyWiiPlaza/JGeckoU#84]
After I use JGecko for a while, a pop up appears on my screen and say it "cannot verify program version," and closes the JGecko window and deletes the .jar file from my computer.

**Comment by BullyWiiPlaza** [comment]
You need to have your Internet enabled and working to avoid this error. Also about the deletion, it was a mistake and will be removed in the next update. Thanks for letting me know.
