### ISSUE TITLE
Downloaded Latest Version

### ISSUE THREAD

**Issue by doinkdoink** [BullyWiiPlaza/JGeckoU#87]
Hi, just downloaded the latest version of it from a few minutes ago, and upon opening, it tells me I do not have the latest version and automatically closes it out. Tried repeating download multiple times and same things keep happening.

Edit, I'm an idiot. Didn't download license too.

**Comment by BullyWiiPlaza** [comment]
Actually, you didn't need to download the license, it just worked because the version information took a little bit to update.
