### ISSUE TITLE
Latest update broke support on Raspberry Pi

### ISSUE THREAD

**Issue by vaguerant** [BullyWiiPlaza/JGeckoU#89]
```
23:51:21.551 [INFO] [main]: ApplicationGUILauncher.main@L165 - Setting look & feel...
23:51:21.965 [INFO] [main]: ApplicationGUILauncher.main@L195 - Setting up thread violations detector...
23:51:24.508 [INFO] [AWT-EventQueue-1]: bN.<init>@L534 - Loading GUI...
Oct 04, 2020 11:51:25 PM bk E
INFO: Getting titles started...
Exception in thread "Thread-7" java.lang.NullPointerException
	at eo.E(qya:70)
	at bN.u(teb:5591)
	at java.lang.Thread.run(Thread.java:748)
```
I haven't used it in a while, so I'm unsure how old my previous install was, but it used to work, and now it doesn't. I tried updating my Java install as well, with no change.

**Comment by BullyWiiPlaza** [comment]
Hi, this is pretty interesting, I will investigate. I can see that the last error you get is already part of the shutdown procedure so it's not related to the initial problem. Why does it shut down already? I guess you didn't close it early. Anyway, I'll let you know about what I can find, I also have a Raspberry Pi.

**Comment by BullyWiiPlaza** [comment]
Hi @vaguerant can you download the new update and try again? I fixed some *nix related bugs. It works well on Ubuntu so it should probably also work on Raspian (again).

**Comment by BullyWiiPlaza** [comment]
I think this should be fixed since my Unix compatibility check-up so I'm closing this issue.
