### ISSUE TITLE
MH3U

### ISSUE THREAD

**Issue by MH3U-WiiU-Hacker** [BullyWiiPlaza/JGeckoU#90]
Hello BullyWiiPlaza i need help for use Jgecko U for MH3U i need help for how to use this item code of MH3U for JGecko U
![Capture d’écran (92)](https://user-images.githubusercontent.com/72657823/95656106-521bd180-0b0c-11eb-838e-972007cebc3c.png)

**Comment by skoolzout1** [comment]
The irony of your name.

**Comment by BullyWiiPlaza** [comment]
Sorry but the GitHub issues are for actual bugs and feature requests and not for asking about end user code help.

It seems like you didn't even put a minimal amount of effort into understanding what you're doing by asking this question and creating an issue without even showing the code in your screenshot.

Anyway, you probably just need to replace the placeholders and then JGecko U should accept your code. Good luck!
