### ISSUE TITLE
Global Settings caused JGecko U to Close after being Launched

### ISSUE THREAD

**Issue by NinAuggie** [BullyWiiPlaza/JGeckoU#91]
Not sure if this issue is major, but i've been noticing that sometimes, when I launch JGecko U, it closes right after I launch it. So, after messing around, I discovered it was because of the Global Settings. So, I removed the Global Settings file and JGecko U launched properly without any problems. Just wondering if this is fixable!

And, great work! I and my friends have had a positive and fun experience with JGecko U!

**Comment by BullyWiiPlaza** [comment]
Thank you! Can you maybe experiment a bit more to figure out exactly which entry in the `Global Settings.properties` file causes the problem? It can be viewed/modified with a simple text editor. Every line entry is a saved setting from the GUI.

**Comment by BullyWiiPlaza** [comment]
Hi @NinAuggie can you download the newest version and see if the issue still happens? Thank you

**Comment by BullyWiiPlaza** [comment]
I think this is no longer relevant so I'm closing this issue.
