### ISSUE TITLE
Code list gets removed when I connect to my Wii U, Won't let me load any list while connected on JGecko U

### ISSUE THREAD

**Issue by fan1glam** [BullyWiiPlaza/JGeckoU#93]
Yeah. Title says it all, I want to use a code list for Minecraft Wii U but whenever I connect to JGecko U it removes the list and I can't load any code list while connected.

**Comment by BullyWiiPlaza** [comment]
You need to save the code list into the `Codes` folder with the right name e.g. `AUMPDU.xml`. You can get the code list file name by connecting to your game, saving your code list and inspecting the `Codes` folder. Also, when you connect, the code list is automatically loaded from the `Codes` folder.
