### ISSUE TITLE
Why not  making it open source?

### ISSUE THREAD

**Issue by nougator** [BullyWiiPlaza/JGeckoU#95]

**Comment by BullyWiiPlaza** [comment]
It was open source until people started to abuse my work for stealing (my) game hacks and besides, nobody ever meaningfully contributed to the development so there was never any point to even make it open source for the benefit of better/faster development. Also now I have donator only features for the years of effort I put into this tool while 99.9% of the community did absolutely nothing besides being leeches and time wasters with regards to pointless and incompetent bug reports and support questions that only prove that most people don't even understand the basics.
